config/routes.rb
Rails.application.routes.draw do
  get 'leaderboard/index'

  get 'main/index'
  root 'contests#index'
  devise_for :users, only: [:passwords, :sessions, :registrations]

  #devise
  #post 'users/sign_in', as: :user_session, controller: 'devise/sessions', action: :create
  #get  'users/sign_in', as: :new_user_session, controller: 'devise/sessions', action: :new
  #delete 'users/sign_out', as: :destroy_user_session, controller: 'devise/sessions', action: :destroy

  post 'challenges/solve', as: :challenge_solve, controller: 'challenges', action: :solve#, defaults: { format: 'json' }

  resources :contests, only: [:index, :show] do
    resources :challenges, only: [:index, :show]
  end
  resources :users, only: [:index, :show] do
    resources :contests, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_and_belongs_to_many :contests, join_table: "challenges_contests"
  has_many :solution
  has_many :hints

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

  def self.validate_solution(answer, challenge_id, user)
    @challenge = Challenge.find(challenge_id)
    hash = Digest::SHA256.hexdigest(answer.downcase.chomp + Rails.application.secrets.challenge_key)
    output = BCrypt::Password.new @challenge.solution_hash
    if output == hash
      s = Solution.new
      s.user =  user
      s.challenge =  @challenge
      user.score += @challenge.score
      user.save
      s.save
      return 'SOLVED'
    else
      return 'WRONG'
    end
  end
end

app/models/contest.rb
class Contest < ApplicationRecord
  include AASM

  has_and_belongs_to_many :challenges, join_table: "challenges_contests"

  def self.check_status
    Contest.where('status = ? or status = ?', 'pending', 'running').each do |c|
      puts c.status
      if c.status == 'running' and Time.now >= c.ends_at
        c.finish!
      elsif c.status == 'pending' and Time.now >= c.begins_at
        c.run!
      end
    end
  end

  aasm column: :status do
    state :pending, initial: true
    state :running
    state :finished

    event :run do
      transitions from: :pending, to: :running
    end

    event :finish do
      transitions from: :running, to: :finished
    end
  end
end

app/models/hint.rb
class Hint < ApplicationRecord
  belongs_to :challenge
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :timeoutable

  before_create :set_score
  has_many :solutions

  private

  def set_score
    self.score = 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_filter :set_locale
  before_filter :authenticate_user!

  def get_user
    @current_user = session[:current_user]
  end

  layout :load_layout

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

  def load_layout
    devise_controller? ? "login" : "application"
  end

  def set_locale
    I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  def show
  end

  def solve
    logger.debug "RECIBIDO: #{challenge_params.inspect}"
    answer = Challenge.validate_solution(challenge_params["solution"], challenge_params["challenge_id"], current_user)
    if request.xhr?
      render json: {status: answer}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def challenge_params
      params.require(:challenge).permit(:id, :name, :challenge_id, :solution)
    end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  def index
    @contests = Contest.all
  end

  # GET /contests/1
  def show
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  def create
    @contest = Contest.new(contest_params)

    if @contest.save
      redirect_to @contest, notice: 'Contest was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contests/1
  def update
    if @contest.update(contest_params)
      redirect_to @contest, notice: 'Contest was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contests/1
  def destroy
    @contest.destroy
    redirect_to contests_url, notice: 'Contest was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contest_params
      params.require(:contest).permit(:name, :begins_at, :ends_at, :status, :rules)
    end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_language
    if I18n.locale =~ /^es.*/
      "spanish"
    else
      "english"
    end
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
  def check_challenge_solved(challenge, user)
    #code
    if user.solutions.pluck(:challenge_id).include? challenge.id
      "&nbsp;&nbsp;&nbsp;<span class='label label-success'>Solved!</span>".html_safe
    end
  end
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/challenges/_form.html.erb
<%= form_for(challenge) do |f| %>
  <% if challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :payload %>
    <%= f.text_area :payload %>
  </div>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Challenges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Payload</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.name %></td>
        <td><%= challenge.description %></td>
        <td><%= challenge.payload %></td>
        <td><%= challenge.score %></td>
        <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<h1>New Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @challenge.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @challenge.description %>
</p>

<p>
  <strong>Payload:</strong>
  <%= @challenge.payload %>
</p>

<p>
  <strong>Score:</strong>
  <%= @challenge.score %>
</p>

<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>

app/views/contests/_challenges.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
<%- @contest.challenges.order(:name).each do |ch| %>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading<%= ch.id %>">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= ch.id %>" aria-expanded="false" aria-controls="collapse<%= ch.id %>">
          <span><%= ch.name %></span><%= check_challenge_solved(ch, current_user) %><span class="pull-right">Score: <%= ch.score %></span>
        </a>
      </h4>
    </div>
    <div id="collapse<%= ch.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%= ch.id %>">
      <div class="panel-body">
        <dl>
          <dd>Description:</dd>
          <dt><%= ch.description.html_safe %></dt>
        </dl>
        <div id="challenge<%= ch.id %>">
          <% if current_user.solutions.pluck(:challenge_id).include? ch.id %>
            <h1 class="label label-success">Solved!</h1>
          <% else %>
            <form id="solution<%= ch.id %>" class="form-inline solution-form" method="post" action="/challenges/solve">
              <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
              <input type="hidden" name="challenge[challenge_id]" value="<%= ch.id %>">
              <label for="solution_input">Solution:&nbsp;</label>
              <input id="solution_input" type="text" name="challenge[solution]">
              <input type="submit" value="Submit">
            </form>
          <% end %>
          <span></span>
        </div>
      </div>
    </div>
  </div>
<%- end %>
</div>

app/views/contests/_form.html.erb
<%= form_for(contest) do |f| %>
  <% if contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :begins_at %>
    <%= f.datetime_select :begins_at %>
  </div>

  <div class="field">
    <%= f.label :ends_at %>
    <%= f.datetime_select :ends_at %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :rules %>
    <%= f.text_area :rules %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing Contest</h1>

<%= render 'form', contest: @contest %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contests</h1>

<table class="table table-bordered table-hover table-stripped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Begins at</th>
      <th>Ends at</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= contest.name %></td>
        <td><%= contest.begins_at.in_time_zone('Buenos Aires').strftime('%d/%m/%Y %H:%M') %></td>
        <td><%= contest.ends_at.in_time_zone('Buenos Aires').strftime('%d/%m/%Y %H:%M') %></td>
        <%- if contest.status == 'running' %>
          <td><%= link_to 'Show', contest %></td>
        <%- else %>
          <td><span class="label label-danger">Contest not started</span></td>
        <%- end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contests/new.html.erb
<h1>New Contest</h1>

<%= render 'form', contest: @contest %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<% if @contest.status != 'running' %>
  <h2>This contest is not currently active</h2>
<% else %>
  <h2><%= @contest.name %></h2>
  <%= render partial: 'challenges' %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><b>C</b>afelug<b> C</b>rypto <b>C</b>hallenge</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if controller_name == 'contests' %>">
          <%= link_to contests_path do %>
            <i class="fa fa-book"></i>
            <span class="menu-title">Contests</span>
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle nav-menu" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span><%= current_user.email %></span>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>&nbsp;<span>Sign out</span>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoChallenge</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
      <div class="container">
        <%= render partial: 'layouts/navbar' %>
      </div>
    </div>
    <div class="row">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="Sebastian A. Espindola">
      <title>BrokerApp</title>
      <%= stylesheet_link_tag 'application', media: 'all' %>
      <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
      <%= javascript_include_tag 'application' %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="col-md-offset-3 col-md-6">
        <% flash.each do |type, message| %>
          <%- next if not message.kind_of? String  or message.empty? %>
          <div class="alert alert-warning alert-dismissible" role="alert">
            <%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
              <i class="fa fa-times"></i></button>
            </button>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/leaderboard/index.html.erb
<h1>Leaderboard#index</h1>
<p>Find me in app/views/leaderboard/index.html.erb</p>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>